// constant about actions

export const REQUEST_API = 'REQUEST_API';
export const REQUEST_API_SUCCESS = 'REQUEST_API_SUCCESS';
export const REQUEST_API_ERROR = 'REQUEST_API_ERROR';

export const REQUEST_API_OFFERS = 'REQUEST_API_OFFERS';
export const REQUEST_API_OFFERS_SUCCESS = 'REQUEST_API_OFFERS_SUCCESS';
export const REQUEST_API_OFFERS_ERROR = 'REQUEST_API_OFFERS_ERROR';

export const ADD_BASKET = 'ADD_BASKET';
export const DELETE_BASKET = 'DELETE_BASKET';